### ISSUE TITLE
tf.assign function error

### ISSUE THREAD

**Issue by trevitran** [MDIL-SNU/SIMPLE-NN#113]
Hello. I am running the example in SiO2/generate_NNP using Python version 3.7.7, Simple-NN version 20.2, and TensorFlow version 2.6.0.

However, I am receiving an error message that states TensorFlow does not have a certain attribute. Do you have any suggestion on how I can resolve this issue? Thanks! 

This is the error message I get when I try to run the run.py script:

Traceback (most recent call last):
  File "run.py", line 7, in <module>
    model=Neural_network())
  File "/share/apps/python-3.7.7/lib/python3.7/site-packages/simple_nn-20.2-py3.7-linux-x86_64.egg/simple_nn/models/neural_network.py", line 93, in __init__
    self.increment_global_step = tf.assign(self.global_step, self.global_step+1)
AttributeError: module 'tensorflow' has no attribute 'assign'

**Comment by JisuJung928** [comment]
Hello, trevitran.

Thanks for using SIMPLE-NN!
The current version of SIMPLE-NN (20.2) supports only TensorFlow 1.x.
Please downgrade your TensorFlow and rerun the script.

P.S.
We are refactoring our code.
Please keep in touch and enjoy a newer code soon.

**Comment by trevitran** [comment]
Thank you for getting back to me! I have downgraded Python version 3.6 and Tensorflow 1.13 but when I try to run the run.py script in the generate_NNP directory I get the same error as before.
