### ISSUE TITLE
Fingerprinting Seg Faults

### ISSUE THREAD

**Issue by bencomer** [MDIL-SNU/SIMPLE-NN#60]
I've been using simple_nn and have run into a few instances where the code terminates in a segmentation fault during fingerprint calculations. I am unable to find the origin of this issue. I've attached a google drive folder that contains the inputs I'm using along with the error message I get in `log`.

[https://drive.google.com/drive/folders/128VUgF4QL0Pb-w8U6-TAzaKCpyhaas0H?usp=sharing](url)

**Comment by Nanco-L** [comment]
In the current version of the code, we assume the PBC cell for x-, y-, and z-direction.
In your example, there is no PBC for z-direction and the coordinates of some atoms are out of the cell boundary. That leads to some problems in our neighboring atom searching algorithm.
Thus, if you want no periodicity for z-direction, we recommend increasing the lattice parameter of z-direction (>cutoff radius) and turning on PBC for all direction. 
To handle this problem, we will add the code for automatically adding vacuum layer for the non-PBC direction of the cell soon.

Kyuhyun

**Comment by bencomer** [comment]
The z-direction actually does have periodicity in the original calculation! (or at least it should, looks like it got messed up somehow.) When I change the periodicity it everything seems to work!
