### ISSUE TITLE
Error: No module named 'simple_nn.utils._libgdf'

### ISSUE THREAD

**Issue by vsumaria** [MDIL-SNU/SIMPLE-NN#65]
I used the install procedure mentioned in the documentation. When trying to import Simple_nn (from simple_nn import Simple_nn), I am getting the following error: 

File "............/softwares/SIMPLE-NN/simple_nn/utils/__init__.py", line 5, in <module>
    from ._libgdf import lib, ffi
ModuleNotFoundError: No module named 'simple_nn.utils._libgdf'

Can you please help me fix this issue ?

**Comment by Nanco-L** [comment]
The module `simple_nn.utils._libgdf` is C++ implementation and automatically complied during the install process. So, please check the installation process (did you use `python setup.py install` command?) and the location you run python. If you do not use the installation command, `libgdf` module is not generated. And, if you try the test in the cloned directory from Github, simple_nn in the cloned directory is imported priory to installed simple_nn. Thus, it also leads to `ModuleNotFoundError`. If you check these two things above and the error still exists, please let me know.

**Comment by vsumaria** [comment]
I did you the install command: python setup.py install —user

Do I need to add any folder to the python path after I do that? I added the SIMPLE-NN main folder to python path . 

Vaidish

**Comment by Nanco-L** [comment]
No. you do not need to add the path. Like pip install, `python setup.py install --user` command install `simple-nn` in your local directory (in common, `~/.local/lib/pythonX.X/site-packages/simple_nn~`). Thus, no additional process is required. But as I mentioned above, if you try to import simple_nn in the cloned directory from Github, `simple_nn` in the cloned directory is imported instead of installed `simple_nn`. So, please try to import `simple_nn` in another directory and remove the path for the `simple-nn` main folder you added.

**Comment by vsumaria** [comment]
It's weird, using just the installation command, it worked on one of the clusters I use, not on the other. Only difference is one is python2.7 (on which it worked) and python3.7 (on which it didn't work) ..

**Comment by Nanco-L** [comment]
Does the same error occur in `python 3.7` cluster? If it does, we will check the `libgdf` compilation in `python 3.7` environments soon. And if another error occurs in your `python 3.7` cluster, please let me know.
p.s. Officially, `simple_nn` supports `python 2.7` and `python 3.4~3.6`.

**Comment by vsumaria** [comment]
It seems to work with 3.7, but there are some warnings that I get, but that is due to some compatibility issue btw tensorflow and numpy 1.17 

If I find any other issues, I will report it here. 

Thanks a lot Kyuhyun
