### ISSUE TITLE
can not install simple-nn with pip

### ISSUE THREAD

**Issue by AlexanderOnly** [MDIL-SNU/SIMPLE-NN#66]
> pip install simple-nn
Collecting simple-nn
  ERROR: Could not find a version that satisfies the requirement simple-nn (from versions: none)
ERROR: No matching distribution found for simple-nn
-----------------------
pip --version
pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by Nanco-L** [comment]
Currently, `simple-nn` cannot be installed by pip. Please download/clone `simple-nn` repository and run the command `python setup.py install` as described in our manual (https://simple-nn.readthedocs.io/en/latest/index.html).
