### ISSUE TITLE
ModuleNotFoundError: No module named 'simple_nn.utils._libgdf'

### ISSUE THREAD

**Issue by AlexanderOnly** [MDIL-SNU/SIMPLE-NN#67]
Hello, I try to run the example SiO2 and I got this Error:
> ModuleNotFoundError: No module named 'simple_nn.utils._libgdf'

<img width="965" alt="屏幕快照 2019-10-07 下午10 20 59" src="https://user-images.githubusercontent.com/18606562/66320495-8422b280-e951-11e9-87e9-42ad2ba86903.png">
Any suggestions?

Thanks,

Alex

**Comment by dkumarrav** [comment]
I am also getting same error 'ModuleNotFoundError: No module named 'simple_nn.utils._libgdf'.
Please let me know how you resolved this issue.
