### ISSUE TITLE
Slightly Inaccurate Fingerprints?

### ISSUE THREAD

**Issue by bencomer** [MDIL-SNU/SIMPLE-NN#68]
Hello,
I was looking over the fingerprints and believe there is a small bug somewhere in their calculation. I built a cell with two oxygens at a distance of 1.2A and used simple_nn to calculate the g2 fingerprint with eta = 0.005 and Rc = 4. When I look at simple_nn's pickle outputs I find the value of 0.7881971276371487 for this fingerprint, but when I do this on my calculator, pure python, and from other NNFF software I get 0.7935354548340433. This is off by ~ 1% but is slightly concerning as the values should be more or less dead on. I have seen a slightly larger difference in the fingerprint primes when comparing to other software as well. Below is my code for calculating the fingerprint value.

```
from ase.build import molecule
import numpy as np

atoms = molecule('O2')
atoms.set_cell([10,10,10])
atoms.positions = np.array([[0,0,0],[0,0,1.2]])
d = atoms.positions[0][2]-atoms.positions[1][2]
print(d)


g2_eta = 0.005
cutoff = 4

g = np.exp(-1 * g2_eta * (d/cutoff) ** 2) * 0.5 * (np.cos(np.pi * (d/cutoff)) + 1)
print(g)
```

**Comment by Nanco-L** [comment]
I think there is an error in your equation.

```
import numpy as np
d = 1.2
g2_eta = 0.005
cutoff = 4.

g = np.exp(-1 * g2_eta * (d/cutoff) ** 2) * 0.5 * (np.cos(np.pi * (d/cutoff)) + 1)
print(g)
>>0.793535454834

g2 = np.exp(-1 * g2_eta * (d) ** 2) * 0.5 * (np.cos(np.pi * (d/cutoff)) + 1)
print(g2)
>>0.788197127637
```

Instead of `d/cutoff`, we use `d`(assume Rs = 0.0) in the exponential term, as described in Behler's paper (https://aip.scitation.org/doi/abs/10.1063/1.3553717?journalCode=jcp).

**Comment by bencomer** [comment]
ah, I see now. It seems that not all NN programs/papers have the same formalism. Thank you!
