### ISSUE TITLE
The example can not run normally

### ISSUE THREAD

**Issue by apmtcc** [MDIL-SNU/SIMPLE-NN#69]
After I successfully install the software (Finished processing dependencies for simple-nn==0.9.0), I run the example and always got the following error:TypeError: read_vasp_out() got an unexpected keyword argument  ‘force_consistent’. Attached please find the detailed information.  Thanks.
![simpleNN-test](https://user-images.githubusercontent.com/51406262/67261910-53a45200-f4d5-11e9-8e84-9ccec732023d.png)
-test.png

**Comment by will1792** [comment]
Currently, SIMPLE-NN has a compatibility issue with ase 3.18. You can downgrade ase from 3.18 to 3.17 to solve the issue. See #64.
