### ISSUE TITLE
ModuleNotFoundError: No module named 'simple_nn.utils._libgdf'

### ISSUE THREAD

**Issue by dkumarrav** [MDIL-SNU/SIMPLE-NN#70]
Hi,
I have installed all the dependencies of SIMPLE-NN but I am getting following error:
>>> import simple_nn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/psrg/software/SIMPLE-NN/simple_nn/__init__.py", line 5, in <module>
    from .utils import modified_sigmoid, _generate_gdf_file
  File "/home/psrg/software/SIMPLE-NN/simple_nn/utils/__init__.py", line 5, in <module>
    from ._libgdf import lib, ffi
ModuleNotFoundError: No module named 'simple_nn.utils._libgdf'

Kindly help me in resolving this issue asap.

**Comment by Nanco-L** [comment]
Hello, dkumarrav. `SIMPLE-NN` has C++ implementations so install process is required to compile these modules. Please check #65.

**Comment by dkumarrav** [comment]
Dear Lee,
Thank you for the reply. However, the problem still persists. I tried to install in other computer still same problem. Although '_libgdf' is generating but python is not recognizing it. I have python 3.6, ase1.18 and tensorflow1.14. I have followed procedure described in SIMPLE_NN manual. Please let me know if I am missing something.

**Comment by dkumarrav** [comment]
Dear Lee,
I installed version-0.9.0 in stead of version-0.8.0 and it is working fine.
