### ISSUE TITLE
Potential Test

### ISSUE THREAD

**Issue by mgp220** [MDIL-SNU/SIMPLE-NN#76]
Hi,
in the documentation (Release 0.7.0) is written that the test_result file includes DFT energies/forces, NNP energies/forces but when I open the file in jupyter, the saved dictionary in the file contains only (dict_keys(['DFT_E', 'NN_E', 'N'])) energies and a third entry named 'N' where only one number per test geometry is saved which is always the same integer number.  I trained the NN for bulk silicon with forces and energy and my question is why I don't get the forces in the test_result file? The input.yaml file which I used for error testing is below

generate_features: false
preprocess: false
train_model: true
atom_types:
 - Si

symmetry_function:
  params:
    Si: params_Si
       
neural_network:
  method: L-BFGS
  nodes: 30-30
  batch_size: 10
  full_batch: true
  train: false
  test: true
  continue: true

**Comment by Nanco-L** [comment]
Dear mgp220,
The default setting of `simple-nn` is training with E only. If you want to train your model with E and F, Please use 'use_force: true' below the 'neural_network:' tag.

**Comment by mgp220** [comment]
Hi Nanco-L
thanks for your fast answer. For training the NN I used the tag  'use_force: true'  but if I want to check the error and use this tag than I get a tensorflow error: 'tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: F (data type: string) is required but could not be found'
So i did the error check without this tag, just as in the documentation but than there are no forces included in the 'test_result'

**Comment by Nanco-L** [comment]
If `use_force: false`, atomic forces are not saved in training dataset. Thus, you need to re-generate dataset with `generate_feature: true`.

**Comment by JisuJung928** [comment]
Dear mgp220
If you upgrade `simple-nn` to the latest version(`6328066`), atomic forces will be just saved in the training dataset even if `use_force: false`.
However, you should still set `use_force: true`, if you want to train or test your potential with atomic force.

**Comment by mgp220** [comment]
Hi all,
thank you very much for your support. The problem is solved.

best regards
