### ISSUE TITLE
Reference data  'utf-8' codec error

### ISSUE THREAD

**Issue by vsumaria** [MDIL-SNU/SIMPLE-NN#83]
I have my reference data as a ASE trajectory file. When I am trying to point to the file in str_list file and running my training I get the following error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 32: invalid continuation byte

my str_list file looks like this: PATH/all_train.traj :

I think the problem is with reading the traj file. I tried to convert it into a xyz traj, but I don't think that is supported. How can I solve this issue?

**Comment by will1792** [comment]
I guess you need to set "refdata_format" in "input.yaml".
For example,
```yaml
symmetry_function:
  params:
    Si: params_Si
  refdata_format: traj
```
The default value is "vasp-out", which is VASP OUTCAR format.
See the [manual](https://simple-nn.readthedocs.io/en/latest/features/symmetry_function/symmetry_function.html?highlight=refdata_format#feature-vector-related-parameter) and see [available formats](https://wiki.fysik.dtu.dk/ase/ase/io/io.html).
