### ISSUE TITLE
params_XX file: type index of neighbor atoms determined by order of elements in input.yaml or alphabetical? 

### ISSUE THREAD

**Issue by EricMusa** [MDIL-SNU/SIMPLE-NN#84]
I want to define a different set of symmetry functions for each element but I am not exactly sure how the "type index of neighbor atoms"is defined. The documentation for the params_XX file says:

> Second and third indicates the type index of neighbor atoms which starts from 1.

How does the index starting at 1 correspond to the elements in the system? Is it from how they're ordered in the input.yaml file? Is it by alphabetical order of the elements? Something else? 

Thanks! - Eric

**Comment by JisuJung928** [comment]
Hello, EricMusa

The element index comes from `atom_types` in `input.yaml`
The element type which comes first has index 1.
