### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by vsumaria** [MDIL-SNU/SIMPLE-NN#85]
I am trying to use simple NN over a large training dataset. My dataset is in ase trajectory file (I have added "refdata_format: traj" in my input.yaml file). Once all the pickle files are for the input dataset are created, the LOG file writes: 
_PATH_/all_train.traj :: ~./data/data20427.pickle

(where all_train.traj is my trajectory file containing 20426 structures)

And my error file gives me the error: 

 File "/u/home/v/vsumaria/.local/lib/python3.6/site-packages/simple_nn-20.1-py3.6-linux-x86_64.egg/simple_nn/utils/__init__.py", line 32, in pickle_load
    return pickle.load(fil, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '\x00'.

Can someone help me understand what is going wrong ?

**Comment by Nanco-L** [comment]
I'm not sure about the exact source of the error but the 20427th pickle file from the trajectory with 20426 structures is weird.
Did you check `data20427.pickle`?
You can check the validity of that file by simply comparing the size of the file with other files.

**Comment by vsumaria** [comment]
I'm sorry I thought the data files started numbering from 0. You are right, I have 20427 images in my traj file. 

The file size is similar to the other pickle files actually. I did check data20427.pickle. Although I did find some other pickle files to be empty (4 to be precise). 

Is there a way to read the generated data.pickle files while running the code again? or does it generate the files again every time ?

**Comment by Nanco-L** [comment]
In `input.yaml`, there are three main tags which activate the main process of `SIMPLE-NN`.
Among them, `generate_feature` tag determines whether new pickle files are generated or not.
If you have valid pickle files, you can set `generate_feature: false` to skip the generation process of pickle file.
Then, `SIMPLE-NN` generates `tfrecord` file from existing pickle files listed in `pickle_list`.
In addition, you can deactivate the preprocessing process by setting `preprocess: false` if you have `tfrecord` files.

**Comment by vsumaria** [comment]
oh, ok. That's very helpful thanks. Will try and remove those pickle files that are empty and try this out. Will let you know if I still have the same issue.

Thanks

**Comment by vsumaria** [comment]
it worked out. After removing the incorrect pickle files, the training is running correctly. Thanks. Closing this issue.
