### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by junwoony** [MDIL-SNU/SIMPLE-NN#86]
Hello, 
I am trying to iteratively generate symmetry functions for atoms.
However, I'm having a memory leak issue. It looks like the memory is not released after computing the symmetry function. Not sure whether I need to use garbage-collector or something similar for C code to release the memory. Do you have any comment or thoughts about it? It's an important issue because I'm trying to iterate the computation for ~1M iterations.

**Comment by JisuJung928** [comment]
Hello junwoony

Yes, I find that there was some dynamic allocation without release in running MD as well as computing the symmetry function.
I fix them and push the new version just before.
Please download the new version and may that it works.
Thanks

**Comment by junwoony** [comment]
@JisuJung928 Now it works without the memory issue.
Thanks!
