### ISSUE TITLE
Use of E_loss and F_loss

### ISSUE THREAD

**Issue by vsumaria** [MDIL-SNU/SIMPLE-NN#89]
Can you help me understand what E_loss and F_loss mean in the code? I tried to go though the documentation but could not find what exactly the function of these two parameters in the yaml file.

**Comment by Nanco-L** [comment]
You can find the definition of E_ and F_loss in our paper
(https://www.sciencedirect.com/science/article/pii/S0010465519301298)
Briefly, E loss is MSE of predicted total energy and DFT total energy and F loss is MSE of predicted atomic force and DFT atomic force.
