### ISSUE TITLE
Scaling taking long time

### ISSUE THREAD

**Issue by vsumaria** [MDIL-SNU/SIMPLE-NN#90]
After the pickle files are generated, the scaling of fingerprints is taking very long. The Log file has not updated for almost 4-5 hours. I don't think it's a memory issue since I have been monitoring the hvmem of my job. Can someone help me troubleshoot this?

**Comment by JisuJung928** [comment]
Hello, vsumaria

Could you explain the detail of the situation?
If you let me know your `input.yaml` and the last part of `LOG`, it would be helpful for me to figure out.
In my experience, when I calculate the scaling factor for too many symmetry functions or use a single core for `GDF`, it takes longer times than usual.

**Comment by vsumaria** [comment]
My input.yaml looks like this:

generate_features: false
preprocess: true
train_model: true
atom_types:
 - Pt
 - C
 - O

symmetry_function:
  params:
    Pt: params_Pt
    C: params_C
    O: params_O
  refdata_format: traj
  atomic_weights:
    type: gdf
    params:
      sigma: Auto

neural_network:
  method: Adam
  nodes: 15-15
  batch_size: 10
  total_iteration: 50000
  learning_rate: 0.001
  use_force: false
  use_stress: false

(I want to only use energy for training)
In the LOG file, the scaling information of Pt and C has been written and the information for O is being written. I am using a large number of symmetry functions (90), but the code only seems to get stuck with 'O', it calculated Pt and C scaling values significantly faster. Is there a way for me to check if the job is being parallelized correctly? Currently in my job script I am requesting 24 core job and submitting the job as "python run.py"

**Comment by JisuJung928** [comment]
According to your `input.yaml`, `LOG`, and submitting command, I think it takes a long time to calculate GDF weight.
If you submit the job without parallelized command such as `mpirun` or `mpiexec` (it depends on your server environment),
python calculates the GDF weight by only a single core.
Please try again with a suitable command.

**Comment by vsumaria** [comment]
When I tried running the code using (mpirun and mpiexec) as "mpirun -n 24 python run.py", I am getting this error which i don't understand:

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    model.run()
  File "/u/home/v/vsumaria/.local/lib/python3.6/site-packages/simple_nn-20.1-py3.6-linux-x86_64.egg/simple_nn/__init__.py", line 194, in run
    **self.descriptor.inputs['atomic_weights']['params'])
  File "/u/home/v/vsumaria/.local/lib/python3.6/site-packages/simple_nn-20.1-py3.6-linux-x86_64.egg/simple_nn/features/symmetry_function/__init__.py", line 337, in preprocess
    comm=comm)
  File "/u/home/v/vsumaria/.local/lib/python3.6/site-packages/simple_nn-20.1-py3.6-linux-x86_64.egg/simple_nn/utils/__init__.py", line 127, in _generate_scale_file
    inp_size = feature_list[item].shape[1]
AttributeError: 'list' object has no attribute 'shape'
/u/local/apps/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprec\
ated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

**Comment by JisuJung928** [comment]
In my experience, I saw the error in that line when the pickle file was not loaded properly. If the pickle file is loaded well, `feature_list[item]` should be array not list. The pickle file is restricted to be loaded by the processor whose rank is 0. Could you test your MPI4PY to check whether it works well or not?
