### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by pulkin** [MDIL-SNU/SIMPLE-NN#91]
~~1. `TypeError: read_vasp_out() got an unexpected keyword argument 'force_consistent'`~~
2. It is particularly hard to install `tf1` because of outdated requirements (specifically, `python3.7`).

**Comment by Nanco-L** [comment]
Hi, we also aware of outdated dependencies but we do not have enough time & developers to update our code.
I recommend using virtualenv or anaconda for older version of Python.
