### ISSUE TITLE
Generating symmetry function features for different atom types

### ISSUE THREAD

**Issue by tanooj-s** [MDIL-SNU/SIMPLE-NN#95]
Sorry if this question is not appropriate but it didn't seem clear in the documentation - how would one go about generating the symmetry function features for different atom types besides the SiO2 example? Specifically I am trying to generate a NN potential using a LAMMPS dump file of NaCl. Would you pass this dump file to the `generate()` function in the `symmetry_function` module somehow?

**Comment by JisuJung928** [comment]
Hello tanooj-s

Your input dataset must contain free energy to build NN potential.
However, LAMMPS dump file does not as far as I know.

If you want to use not VASP OUTCAR format (default), modify `refdata_format` tag in `symmetry_function` of `input.yaml`.
Please refer to this page [refdata_format](https://wiki.fysik.dtu.dk/ase/ase/io/io.html)

Additionally, if you are interested in symmetry function input parameter `params_XX`, [our documentation](https://simple-nn.readthedocs.io/en/latest/features/symmetry_function/symmetry_function.html) will be helpful.

**Comment by tanooj-s** [comment]
Hi JisuJung928. Thanks for your reply. I am still a little unclear about how one would generate the coefficients within the `params_XX` file for a different atom type.

**Comment by JisuJung928** [comment]
As you can see, the coefficients within the `params_XX` do not depend on their chemical properties.
It is a kind of hyperparameter only based on cartesian geometry.
Therefore, you can use `params_XX` in the example directory in any binary system.
You just delete/insert rows for that atoms types to generate `params_XX` for unary or ternary.
If you have any remaining questions, feel free to ask.

**Comment by tanooj-s** [comment]
Ah ok got it thank you. But the parameters would then still depend on the coordination/crystal structure of the material?

**Comment by JisuJung928** [comment]
Parameters are similar to the "kernel function" (I'm not sure this expression is appropriate..)
The symmetry function value contains the geometry characteristic of materials so that NNP can detect them.
You don't need to worry about the geometry of materials when you set parameters.

**Comment by tanooj-s** [comment]
Ok I believe I just need to read the original paper more carefully. Thanks for answering my questions!
